# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13D0niPMtWT9EYytar3QHpTtwfR5X6AQg

# **# Exercicios Iniciais**

### **Ex 1**
"""

a = 4
b = 10
x = a + b
print(x)

"""### **Ex 2**"""

pi = 3.14159
r = 2
area = pi * (r**2)
print(area)
round(area, 3)

"""### **Ex 3**"""

def media(lista):
   return  sum(lista) / len(lista)

media ([5, 6, 7])

"""### **Ex 4**"""

a = 3.0
b = 4.0
c = 5.2

def area1(a, c):
   area1 = (a * c) / 2
   return area1

area1(3.0, 5.2)

pi = 3.14159
def area2(c):
  area2 = pi * c**2
  return area2

area2(5.2)
round(area2(5.2), 3)

def area3(a, b, c):
  area3 = (a + b) / 2 * c
  return area3

area3(3.0, 4.0, 5.2)

def area4 (b):
  area4 = b**2
  return area4

area4(4.0)

def area5(a, b):
  area5 = a * b 
  return area5

area5 (3.0, 4.0)

"""### **Ex 5**"""

def distancia (x1, y1, x2, y2):
  distancia = ((x2 - x1)**2 + (y2 - y1)**2)**(0.5)
  return distancia
distancia(1.0, 7.0, 5.0, 9.0)
round(distancia(1.0, 7.0, 5.0, 9.0), 4)

"""### **Ex 6**"""

number = [1, 2, 3, ..., 25]

recebe_hora = 5.50
def funcionario (horas, recebe_hora):
  sálario = horas * recebe_hora 
  return sálario

print(number [-1])

funcionario (100, 5.5)
print("R$", funcionario(100, 5.5))

"""### **Ex 7**"""

idade = 800 
mes = 30 
ano = 365
idade_anos = idade / ano
idade_meses = idade / mes
idade_anos_meses_dias = idade_anos / idade_meses



"""### **Ex 8**"""

a = 10
b = 20.1
c = 5.1

def R1 (a, b, c):
  R1 = (-b + (b**2 - (4 * a * c))**(0.5)) / (2 * a)
  return R1
def R2 (a, b ,c):
  R2 = (-b - (b**2 - (4 * a * c))**(0.5)) / (2 * a)
  return R2

if (2 * a) == 0:
  print("IMPOSSIVEL CALCULAR")
if (b**2 - (4 * a * c)) < 0:
  print("IMPOSSIVEL CALCULAR")
else:
  print(R1(a, b, c), R2(a, b, c))

R1(10.0, 20.1, 5.1)

"""### **Ex 9**"""

DDD = [61, 71, 11, 21, 32, 19, 27, 31, 55]
Destino = ['Brasilia','Salvador', 'Sao_Paulo', 'Rio_de_Janeiro', 'Juiz_de_Fora', 'Campinas', 'Vitoria', 'Belo_Horizonte', 'Santa_Maria']
DDD[0:8] = Destino [0:8]
def Destino():
  return

def telefone(DDD):
  if DDD == 61:
    print('Brasilia')
  elif DDD == 71:
    print('Salvador')
  else:
    print('DDD nao cadastrado')

telefone(DDD = 100)

"""### **Ex 10**"""

a = float(input('digite seu numero favorito'))
print(a + 5)

n_jogos = 0
n_vitoria_inter = 0
n_vitoria_gremio = 0
n_empates = 0
n_gols_i = float(input('digite o numero de gols do inter aqui'))
n_gols_g = float(input('digite o numero de gols do gremio aqui'))

if n_gols_i > n_gols_g:
  n_vitoria_inter = n_vitoria_inter + 1
elif n_gols_g > n_gols_i:
  n_vitoria_gremio = n_vitoria_gremio + 1
else:
  n_empates = n_empates + 1

while float(input('Deseja continuar? 1-Sim, 2-Nao')) == 1:
  n_gols_i = float(input('digite o numero de gols do inter aqui'))
  n_gols_g = float(input('digite o numero de gols do gremio aqui'))
  if n_gols_i > n_gols_g:
    n_vitoria_inter = n_vitoria_inter + 1
  elif n_gols_g > n_gols_i:
    n_vitoria_gremio = n_vitoria_gremio + 1
  else:
    n_empates = n_empates + 1

print(n_vitoria_inter)
print(n_vitoria_gremio)

"""### **Ex 11**"""

P = 1
C = 2
P = float(input('P <= 5' and 'P >= 1')) 
C = float(input('C >= 2' and 'C <=100'))

if P < C:
  print('GAME OVER')
if C <= P:
  print('YOU WIN')

P <= 5 and P >= 1
C <= 100 and C >= 2

"""### **Ex 12**"""

T = 1
concorrentes = [a, b, c, d, e]
a = 1
b = 2
c = 3
d = 2
e = 1
respostas_corretas = 0

while
  respostas_corretas = respostas_corretas + 1